---
- name: Install Git
  apt: name={{item}} state=installed
  with_items:
    - git-gui
    - gitk
  become: true
- name: Install Yakuake, Kate, Okteta, Kompare
  apt: name={{item}} state=installed
  with_items:
    - yakuake
    - kate
    - okteta
    - kompare
  become: true
- name: Install additional KDE software and helpers
  apt: name={{item}} state=installed
  with_items:
    - ktexteditorpreviewplugin
    - kmarkdownwebview
  become: true
- name: Copy default configuration file for Kate
  copy:
    src: katepartrc
    dest: "{{homedir}}/.config/katepartrc"
    force: no
- name: Kate - Set remove spaces
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Remove Spaces='
    insertafter: '^[Document]'
    line: "Remove Spaces=2"
- name: Kate - Append newline at end of file
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Newline at End of File='
    insertafter: '^[Document]'
    line: "Newline at End of File=true"
- name: Kate - Show word wrap maker
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Word Wrap Marker='
    insertafter: '^[Document]'
    line: "Word Wrap Marker=true"
- name: Kate - Show line numbers
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Line Numbers='
    insertafter: '^[View]'
    line: "Line Numbers=true"
- name: Kate - Show line modification markers
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Line Modification='
    insertafter: '^[View]'
    line: "Line Modification=true"
- name: Kate - Animate bracket matching
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Animate Bracket Matching='
    insertafter: '^[Renderer]'
    line: "Animate Bracket Matching=true"
- name: Kate - Show spaces
  lineinfile:
    destfile: "{{homedir}}/.config/katepartrc"
    regexp: 'Show Spaces='
    insertafter: '^[Document]'
    line: "Show Spaces=true"
- name: Copy default configuration file for Kwrite
  copy:
    src: kwriterc
    dest: "{{homedir}}/.config/kwriterc"
    force: no
- name: Kwrite - Show full path in title bar
  lineinfile:
    destfile: "{{homedir}}/.config/kwriterc"
    regexp: 'ShowPath='
    insertafter: '^[General Options]'
    line: "ShowPath=true"
- name: Disable automatic screen locking (category)
  lineinfile:
    destfile: "{{homedir}}/.config/kscreenlockerrc"
    line: "[Daemon]"
- name: Disable automatic screen locking
  lineinfile:
    destfile: "{{homedir}}/.config/kscreenlockerrc"
    regexp: '^Autolock='
    insertafter: "[Daemon]"
    line: "Autolock=false"
- name: Copy bashrc
  copy:
    src: bashrc
    dest: "{{homedir}}/.bashrc"
- name: Copy keyboard configuration
  copy:
    src: kxkbrc
    dest: "{{homedir}}/.config/kxkbrc"
- name: Copy configuration file of Yakuake
  copy:
    src: yakuakerc
    dest: "{{homedir}}/.config/yakuakerc"
- name: Copy file for not showing notifcation at start of Yakuake
  copy:
    src: yakuake.notifyrc
    dest: "{{homedir}}/.config/yakuake.notifyrc"
- name: Make sure that the autostart directory exists
  file:
    path: "{{homedir}}/.config/autostart"
    state: directory
    recurse: yes
- name: Copy file for automatically starting Yakuake
  copy:
    src: yakuake.desktop
    dest: "{{homedir}}/.config/autostart/yakuake.desktop"
